name = "aiken-lang/vestingnew"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/vestingnew'"

[repository]
user = "aiken-lang"
project = "vestingnew"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
